<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="Heater_control" Id="{dd38d42a-bd3b-456e-a2fc-9f69da39d4fa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Heater_control
VAR_INPUT
	Resistance: LREAL;
	desiredTemp:LREAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	state: LREAL;
	temperature :LREAL;
	error: LREAL; // E(k)
	previousError: LREAL; // E(k-1)
	PWM: FB_PWM;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="Heater_control">
      <LineId Id="26" Count="0" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>