<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="HeaterCatridge_control" Id="{dd38d42a-bd3b-456e-a2fc-9f69da39d4fa}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HeaterCatridge_control
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="HeaterCatridge_control">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>