<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PWM_control" Id="{97f2005f-88d7-4913-9e3e-876430c870ed}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK PWM_control
VAR_INPUT
	dutyCycle: LREAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PWM_control">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>